# Generated by Django 3.0.2 on 2021-02-24 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0011_auto_20210224_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentform',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allcomments', to='loginapp.Blogpost'),
        ),
    ]
